server:
  address: 0.0.0.0
  port: 8181
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-enums-using-index: true
      write-enum-keys-using-index: true
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:15432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin123
    hikari:
      idle-timeout: 10000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

  flyway:
    url: jdbc:postgresql://localhost:15432/postgres
    user: postgres
    password: admin123
    locations: classpath:db/migration/

  profile:
    active: dev
logging:
  level:
    root: INFO
    org.package: INFO