server:
  address: 0.0.0.0
  port: 8181
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-enums-using-index: true
      write-enum-keys-using-index: true
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      idle-timeout: 10000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
    console:
      path: /h2-ui

logging:
  level:
    root: INFO
    org.package: INFO
#
#  flyway:
#    url: jdbc:h2:mem:testdb
#    user: sa
#    password: password
#    locations: classpath:db/migration/